[project]
name = "ManyTypes"
msvc-runtime="dynamic"
include-before = [
    "cmake/msvc-static-runtime.cmake",
    "cmake/msvc-configurations.cmake",
]

[fetch-content.x64dbg]
url = "https://sourceforge.net/projects/x64dbg/files/snapshots/snapshot_2025-03-15_15-57.zip"
include-after = ["cmake/x64dbg.cmake"]

[conditions]
x32 = "CMAKE_SIZEOF_VOID_P EQUAL 4"
x64 = "CMAKE_SIZEOF_VOID_P EQUAL 8"

[target.libclang]
type = "interface"
include-directories = ["extern/include"]
x32.link-libraries = ["extern/lib/x32/libclang.lib"]
x64.link-libraries = ["extern/lib/x64/libclang.lib"]

[target.manytypes-lib]
type = "library"
sources = ["manytypes-lib/src/**"]
headers = ["manytypes-lib/include/**"]
compile-features = ["cxx_std_23"]
link-libraries = ["::libclang"]
include-directories = ["manytypes-lib/include"]

[target.manytypes-sandbox]
type = "executable"
sources = ["manytypes-sandbox/**"]
headers = ["manytypes-sandbox/**"]
compile-features = ["cxx_std_23"]
link-libraries = ["::manytypes-lib"]

[template.plugin]
type = "shared"
add-function = "x64dbg_plugin"

[target.manytypes-plugin]
type = "plugin"
msvc-runtime="static"
sources = ["manytypes-plugin/**"]
headers = ["manytypes-plugin/**"]
link-libraries = ["::manytypes-lib"]
compile-features = ["cxx_std_23"]
